name: Deploy TikTok Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS via SSH Password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/tiktok_bot
            git pull origin main
            source /root/shared_env/bin/activate
            pip install -r requirements.txt
            systemctl restart tiktok
